# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Locale-Maketext-Pseudo
version:      v0.0.3
version_from: lib/Locale/Maketext/Pseudo.pm
installdirs:  site
requires:
    Test::More:                    0
    Test::Perl::Critic:            0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
